strategy: ddp
benchmark: True
pretrained: False
sync_batchnorm: False
clip_grad: null
precision: 16
epochs: &epochs 200
# --------------------------------------
# Dataset parameters
# --------------------------------------
train_dataset:
  name: LiDARAndPseudoLabeledTrainingDataset
  params:
    data_path: &data_path data/mmfi.pkl
    split: [train_rdn_p3, val_rdn_p3]
    ratio: 0.1
    data_path_pl: data/mmfi_pred.pkl
    data_path_ref: data/hmpear.pkl
    split_ref: [train, val]
val_dataset:
  name: BaseDataset
  params:
    data_path: *data_path
    split: test_rdn_p3
test_dataset:
  name: BaseDataset
  params:
    data_path: data/mmfi.pkl
    split: test_rdn_p3
predict_dataset:
  name: BaseDataset
  params:
    data_path: data/mmfi.pkl
    split: [train_rdn_p3, val_rdn_p3]
# --------------------------------------
# Optimizer parameters
# --------------------------------------
optim_name: AdamW
optim_params:
  lr: 0.0001
  weight_decay: 0.00001
# --------------------------------------
# Learning rate scheduler parameters
# --------------------------------------
sched_name: LinearWarmupCosineAnnealingLR
sched_params:
  warmup_epochs: 40
  max_epochs: *epochs
  warmup_start_lr: 0.00001
  eta_min: 0.00001
# --------------------------------------
# Model parameters
# --------------------------------------
lemt_train: True
model_name: P4Transformer
model_params:
  radius: 0.7
  nsamples: 32
  spatial_stride: 8
  temporal_kernel_size: 3
  temporal_stride: 1
  emb_relu: false
  dim: 1024
  depth: 5
  heads: 8
  dim_head: 128
  mlp_dim: 2048
  output_dim: 45
  features: 1
# --------------------------------------
# Loss parameters
# --------------------------------------
loss_name: UnsupLoss
loss_params:
  thres_static: 0.2
  thres_dynamic: 0.1
  thres_loss: 0.1
pl_weight: 0.1
lidar_weight: 1.0
# --------------------------------------
# Augmentation parameters
# --------------------------------------
train_pipeline:
  - name: UniformSample
    params: 
      pad_type: 'start'
      clip_len: 7
      offset: 1
  - name: GetCentroid
    params: 
      centroid_type: 'kps'
  - name: Normalize
    params:
      feat_scale: null
  - name: MultiFrameAggregate
    params:
      num_frames: 3
  - name: ToITOP
    params: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 1.5
  - name: RandomScale
    params:
      scale_min: 0.9
      scale_max: 1.1
    prob: 0.5
  - name: RandomRotate
    params:
      deg: true
      angle_min: -10
      angle_max: 10
    prob: 0.5
  - name: RandomTranslate
    params:
      translate_range: 0.01
    prob: 0.5
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'end'
      frame_to_reduce: 0
  - name: Pad
    params:
      max_len: 256
  - name: RandomJitter
    params:
      jitter_std: 0.05
    prob: 0.5
  - name: ToTensor
    params: null
val_pipeline: &val_pipeline
  - name: UniformSample
    params:
      pad_type: 'start'
      clip_len: 7
      offset: 1
  - name: GetCentroid
    params: 
      centroid_type: 'kps'
  - name: ToITOP
    params: null
  - name: MultiFrameAggregate
    params:
      num_frames: 3
  - name: Normalize
    params:
      feat_scale: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 1.5
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'end'
      frame_to_reduce: 0
  - name: Pad
    params:
      max_len: 256
  - name: ToTensor
    params: null
test_pipeline: &test_pipeline
  - name: UniformSample
    params:
      pad_type: 'start'
      clip_len: 7
      offset: 1
  - name: GetCentroid
    params: 
      centroid_type: 'kps'
  - name: ToITOP
    params: null
  - name: MultiFrameAggregate
    params:
      num_frames: 3
  - name: Normalize
    params:
      feat_scale: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 1.5
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'end'
      frame_to_reduce: 0
  - name: Pad
    params:
      max_len: 256
  - name: ToTensor
    params: null
pl_pipeline:
  - name: UniformSample
    params:
      pad_type: 'start'
      clip_len: 7
      offset: 1
  - name: GetCentroid
    params: 
      centroid_type: 'kps'
  - name: MultiFrameAggregate
    params:
      num_frames: 3
  - name: Normalize
    params:
      feat_scale: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 1.5
  - name: RandomScale
    params:
      scale_min: 0.9
      scale_max: 1.1
    prob: 0.5
  - name: RandomRotate
    params:
      deg: true
      angle_min: -10
      angle_max: 10
    prob: 0.5
  - name: RandomTranslate
    params:
      translate_range: 0.01
    prob: 0.5
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'end'
      frame_to_reduce: 0
  - name: Pad
    params:
      max_len: 256
  - name: ToTensor
    params: null
ref_pipeline: 
  - name: UniformSample
    params: 
      pad_type: 'start'
      clip_len: 6
  - name: GetCentroid
    params: 
      centroid_type: 'kps'
  - name: Normalize
    params:
      feat_scale: null
  - name: ToITOP
    params: null
  - name: RemoveOutliers
    params: 
      outlier_type: 'box'
      radius: 1.5
  - name: AddNoisyPoints
    params:
      add_std: 1.0
      num_added: 32
      zero_centered: false
    prob: 0.5
  - name: FlowBasedPointFiltering
    params:
      max_dist_threshold: 0.1
      min_dist_threshold: 0.02
  - name: RandomScale
    params:
      scale_min: 0.9
      scale_max: 1.1
    prob: 0.5
  - name: RandomRotate
    params:
      deg: true
      angle_min: -10
      angle_max: 10
    prob: 0.5
  - name: RandomTranslate
    params:
      translate_range: 0.01
    prob: 0.5
  - name: ReduceKeypointLen
    params:
      only_one: true
      keep_type: 'end'
      frame_to_reduce: 0
  - name: Pad
    params:
      max_len: 256
  - name: RandomJitter
    params:
      jitter_std: 0.05
    prob: 0.5
  - name: ToTensor
    params: null
predict_pipeline: *test_pipeline